[package]
name = "foxa-lexer"
description = "Lexical analyzer for the Foxa programming language"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
foxa-span = { workspace = true }
foxa-diagnostics = { workspace = true }

[dev-dependencies]
