[package]
name = "foxa-resolve"
description = "Symbol tables, scopes, and name resolution for Foxa"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
foxa-span = { workspace = true }
foxa-diagnostics = { workspace = true }
foxa-ast = { workspace = true }

[dev-dependencies]
foxa-lexer = { workspace = true }
foxa-parser = { workspace = true }
