[package]
name = "foxa-parser"
description = "Pratt + recursive-descent parser for Foxa"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
foxa-span = { workspace = true }
foxa-diagnostics = { workspace = true }
foxa-lexer = { workspace = true }
foxa-ast = { workspace = true }

[dev-dependencies]
